services:
  parser:
    image: php:8.2-fpm
    container_name: parser
    volumes:
      - ./src:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./composer.json:/var/www/composer.json
      - ./vendor:/var/www/vendor
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - parser

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: ["composer", "install"]

volumes:
  db_data:
